import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const augusta = localFont({ src: "../fonts/Augusta.ttf" });

const warsuck = localFont({ src: "../fonts/Warsuck.ttf" });

export const metadata: Metadata = {
  title: "La leyenda de Nova Terra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={warsuck.className}>{children}</body>
    </html>
  );
}
