import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const augusta = localFont({
  src: '../fonts/Augusta.ttf',
  display: 'swap',
  variable: '--font-augusta',
});

const warsuck = localFont({
  src: '../fonts/Warsuck.ttf',
  display: 'swap',
  variable: '--font-warsuck',
});

const frizQuadrata = localFont({
  src: '../fonts/FrizQuadrata.ttf',
  display: 'swap',
  variable: '--font-friz-quadrata',
});

export const metadata: Metadata = {
  title: 'La leyenda de Nova Terra',
  description: 'Generated by create next app',
};

/**
 * Root layout component.
 *
 * @param {Object} props - The component props.
 * @param {React.ReactNode} props.children - The child components to render.
 * @returns {JSX.Element} The rendered root layout component.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${warsuck.variable} ${augusta.variable} ${frizQuadrata.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
